<?php
declare(strict_types=1);

// LmEmail SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

LmEmailUtility::setRegistrar(function (LmEmailUtility $u): void {
    $u->clean = [LmEmailClean::class, 'call'];
    $u->done = [LmEmailDone::class, 'call'];
    $u->make_error = [LmEmailMakeError::class, 'call'];
    $u->feature_add = [LmEmailFeatureAdd::class, 'call'];
    $u->feature_hook = [LmEmailFeatureHook::class, 'call'];
    $u->feature_init = [LmEmailFeatureInit::class, 'call'];
    $u->fetcher = [LmEmailFetcher::class, 'call'];
    $u->make_fetch_def = [LmEmailMakeFetchDef::class, 'call'];
    $u->make_context = [LmEmailMakeContext::class, 'call'];
    $u->make_options = [LmEmailMakeOptions::class, 'call'];
    $u->make_request = [LmEmailMakeRequest::class, 'call'];
    $u->make_response = [LmEmailMakeResponse::class, 'call'];
    $u->make_result = [LmEmailMakeResult::class, 'call'];
    $u->make_point = [LmEmailMakePoint::class, 'call'];
    $u->make_spec = [LmEmailMakeSpec::class, 'call'];
    $u->make_url = [LmEmailMakeUrl::class, 'call'];
    $u->param = [LmEmailParam::class, 'call'];
    $u->prepare_auth = [LmEmailPrepareAuth::class, 'call'];
    $u->prepare_body = [LmEmailPrepareBody::class, 'call'];
    $u->prepare_headers = [LmEmailPrepareHeaders::class, 'call'];
    $u->prepare_method = [LmEmailPrepareMethod::class, 'call'];
    $u->prepare_params = [LmEmailPrepareParams::class, 'call'];
    $u->prepare_path = [LmEmailPreparePath::class, 'call'];
    $u->prepare_query = [LmEmailPrepareQuery::class, 'call'];
    $u->graphql_body = [LmEmailGraphql::class, 'body'];
    $u->graphql_errors = [LmEmailGraphql::class, 'errors'];
    $u->result_basic = [LmEmailResultBasic::class, 'call'];
    $u->result_body = [LmEmailResultBody::class, 'call'];
    $u->result_headers = [LmEmailResultHeaders::class, 'call'];
    $u->transform_request = [LmEmailTransformRequest::class, 'call'];
    $u->transform_response = [LmEmailTransformResponse::class, 'call'];
});
